spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/statistic_service
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog.xml
  docker-compose:
    format: yml
  docker:
    compose:
      enabled: true
      file: classpath:/docker-compose.yml
  web:
    resources:
      add-mappings: false
server:
  port: 8093
  error:
    whitelabel:
      enabled: false
