name: 🔥 Сборка и тесты МР-а

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 👉🏼 Переключаемся на файлы проекта
        uses: actions/checkout@v3

      - name: 👉🏼 Инициализируем гит сабмодули
        run: |
          git submodule update --init --remote --recursive
          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'

      - name: 👉🏼 Настройка JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 👉🏼 Запускаем сборку без тестов
        run: mvn clean package -DskipTests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 👉🏼 Переключаемся на файлы проекта
        uses: actions/checkout@v3

      - name: 👉🏼 Инициализируем гит сабмодули
        run: |
          git submodule update --init --remote --recursive
          git submodule foreach 'git checkout ${GITHUB_REF##*/} && git pull || echo "In ${sm_path} branch ${GITHUB_REF##*/} not found"'

      - name: 👉🏼 Настройка JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 👉🏼 Запускаем тесты
        run: mvn clean package